/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Tutor CRM API
 * The ultimate API for managing tutors, students, and finances.
 * OpenAPI spec version: 1.0
 */

export type CreateLessonDtoStatus = typeof CreateLessonDtoStatus[keyof typeof CreateLessonDtoStatus];


export const CreateLessonDtoStatus = {
  PLANNED: 'PLANNED',
  COMPLETED: 'COMPLETED',
  CANCELED: 'CANCELED',
  MISSED: 'MISSED',
} as const;
