/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Tutor CRM API
 * The ultimate API for managing tutors, students, and finances.
 * OpenAPI spec version: 1.0
 */
import type { CreateTransactionDtoType } from './createTransactionDtoType';

export interface CreateTransactionDto {
  /** ID ученика */
  studentId: string;
  /**
     * Сумма транзакции
     * @minimum 1
     */
  amount: number;
  /** Тип транзакции */
  type: CreateTransactionDtoType;
  /** ID урока (если это списание за конкретный урок) */
  lessonId?: string;
}
