/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Tutor CRM API
 * The ultimate API for managing tutors, students, and finances.
 * OpenAPI spec version: 1.0
 */
import type { CreateContactDtoType } from './createContactDtoType';

export interface CreateContactDto {
  /** ID ученика (передавать, если контакт для ученика) */
  studentId?: string;
  /** ID родителя (передавать, если контакт для родителя) */
  parentId?: string;
  type: CreateContactDtoType;
  value: string;
  /** Кастомное название (только для типа CUSTOM) */
  customLabel?: string;
}
