/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Tutor CRM API
 * The ultimate API for managing tutors, students, and finances.
 * OpenAPI spec version: 1.0
 */

/**
 * Тип транзакции
 */
export type CreateTransactionDtoType = typeof CreateTransactionDtoType[keyof typeof CreateTransactionDtoType];


export const CreateTransactionDtoType = {
  PAYMENT: 'PAYMENT',
  CHARGE: 'CHARGE',
} as const;
