/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Tutor CRM API
 * The ultimate API for managing tutors, students, and finances.
 * OpenAPI spec version: 1.0
 */

export type CreateContactDtoType = typeof CreateContactDtoType[keyof typeof CreateContactDtoType];


export const CreateContactDtoType = {
  PHONE: 'PHONE',
  TELEGRAM: 'TELEGRAM',
  VIBER: 'VIBER',
  WHATSAPP: 'WHATSAPP',
  VK: 'VK',
  DISCORD: 'DISCORD',
  CUSTOM: 'CUSTOM',
} as const;
