/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Tutor CRM API
 * The ultimate API for managing tutors, students, and finances.
 * OpenAPI spec version: 1.0
 */

export * from './createContactDto';
export * from './createContactDtoType';
export * from './createLessonDto';
export * from './createLessonDtoStatus';
export * from './createLessonTemplateDto';
export * from './createParentDto';
export * from './createStudentDto';
export * from './createTransactionDto';
export * from './createTransactionDtoType';
export * from './loginDto';
export * from './nestedContactDto';
export * from './nestedContactDtoType';
export * from './nestedParentDto';
export * from './registerDto';
export * from './studentsControllerFindAllParams';
export * from './studentsControllerFindAllSortBy';
export * from './studentsControllerFindAllSortOrder';
export * from './studentsControllerUploadAvatarBody';
export * from './updateContactDto';
export * from './updateContactDtoType';
export * from './updateLessonDto';
export * from './updateLessonDtoStatus';
export * from './updateLessonTemplateDto';
export * from './updateParentDto';
export * from './updateStudentDto';
