/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Tutor CRM API
 * The ultimate API for managing tutors, students, and finances.
 * OpenAPI spec version: 1.0
 */
import type { NestedContactDtoType } from './nestedContactDtoType';

export interface NestedContactDto {
  type: NestedContactDtoType;
  value: string;
  customLabel?: string;
}
