/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Tutor CRM API
 * The ultimate API for managing tutors, students, and finances.
 * OpenAPI spec version: 1.0
 */

export interface RegisterDto {
  email: string;
  /** @minLength 6 */
  password: string;
  /** @minLength 2 */
  name: string;
}
