/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Tutor CRM API
 * The ultimate API for managing tutors, students, and finances.
 * OpenAPI spec version: 1.0
 */
import type { StudentsControllerFindAllSortBy } from './studentsControllerFindAllSortBy';
import type { StudentsControllerFindAllSortOrder } from './studentsControllerFindAllSortOrder';

export type StudentsControllerFindAllParams = {
/**
 * Номер страницы
 * @minimum 1
 */
page?: number;
/**
 * Количество на странице
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Поиск по имени (регистронезависимый)
 */
search?: string;
/**
 * Поле для сортировки
 */
sortBy?: StudentsControllerFindAllSortBy;
sortOrder?: StudentsControllerFindAllSortOrder;
/**
 * Показать только архивных учеников
 */
isArchived?: boolean;
};
