/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Tutor CRM API
 * The ultimate API for managing tutors, students, and finances.
 * OpenAPI spec version: 1.0
 */

export type StudentsControllerFindAllSortBy = typeof StudentsControllerFindAllSortBy[keyof typeof StudentsControllerFindAllSortBy];


export const StudentsControllerFindAllSortBy = {
  createdAt: 'createdAt',
  name: 'name',
} as const;
