/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Tutor CRM API
 * The ultimate API for managing tutors, students, and finances.
 * OpenAPI spec version: 1.0
 */

export interface UpdateParentDto {
  /**
     * @minLength 2
     * @maxLength 255
     */
  name?: string;
}
