/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Tutor CRM API
 * The ultimate API for managing tutors, students, and finances.
 * OpenAPI spec version: 1.0
 */

export interface UpdateLessonTemplateDto {
  /**
     * День недели (1 = Понедельник, 7 = Воскресенье)
     * @minimum 1
     * @maximum 7
     */
  dayOfWeek?: number;
  /** Время начала урока */
  startTime?: string;
  /**
     * Продолжительность в минутах
     * @minimum 15
     */
  durationMinutes?: number;
  /**
     * Стоимость урока по умолчанию
     * @minimum 0
     */
  defaultPrice?: number;
  /**
     * Интервал в неделях (по умолчанию 1 - каждую неделю)
     * @minimum 1
     */
  intervalWeeks?: number;
  /** Дата первого занятия */
  firstLessonDate?: string;
}
