/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Tutor CRM API
 * The ultimate API for managing tutors, students, and finances.
 * OpenAPI spec version: 1.0
 */
import type { UpdateContactDtoType } from './updateContactDtoType';

export interface UpdateContactDto {
  type?: UpdateContactDtoType;
  value?: string;
  /** Кастомное название (только для типа CUSTOM) */
  customLabel?: string;
}
