/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Tutor CRM API
 * The ultimate API for managing tutors, students, and finances.
 * OpenAPI spec version: 1.0
 */
import type { UpdateLessonDtoStatus } from './updateLessonDtoStatus';

export interface UpdateLessonDto {
  /** ID ученика, которому назначается урок */
  studentId?: string;
  /** Дата и время урока в формате ISO (например, 2026-03-27T15:00:00.000Z) */
  scheduledAt?: string;
  /**
     * Стоимость (если не передать, возьмется из профиля ученика)
     * @minimum 0
     */
  priceToCharge?: number;
  status?: UpdateLessonDtoStatus;
}
